# Site settings
title: Yolanda's Blog
tagline: Always keep mind sharp
SEOTitle: 美嘉的博客 | Yolanda Blog
#header-img: img/post-bg-desk.jpg
email: mathselse@gmail.com
description: "Keep Mind Sharp"
keyword: ""
url: "http://yolandaleo.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/YolandaLeo/yolandaleo.github.io.git" # you code repository
site.author.name: "Meijia Lyu"

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems:
  - jekyll-paginate

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge                       # use Github Flavored Markdown !important

excerpt_separator: "<!--more-->"

sass:
  style: compressed
  sass_dir: _scss

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# About/contact
author:
  name: Yolanda
  description: A passionate developer and a continuous learner
  contact:
    linkedin:  https://www.linkedin.com/in/meijia-lyu-5649a1a5/
    github:    https://github.com/YolandaLeo
    email:     mathselse@gmail.com
# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:  
    - '/blog/'         
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/YolandaLeo/yolandaleo.github.io'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'
